# Generated by migeval bootstrap — review before committing
"""
AST-aware detectors for PatternFly 5 → 6 migration issues.

Scans source files for migration problems that simple regex patterns cannot catch,
such as cross-file consistency issues, component+prop combinations, and structural
patterns.
"""

import hashlib
import json
import re
from pathlib import Path
from typing import Any


def _make_id(detector_id: str, file: str, extra: str = "") -> str:
    """Generate a deterministic issue ID."""
    key = f"source_detector|{detector_id}|{file}|{extra}"
    return hashlib.sha256(key.encode()).hexdigest()[:16]


def _source_files(root: Path, extensions: tuple[str, ...] = (".tsx", ".ts", ".jsx", ".js")) -> list[Path]:
    """Walk root for source files with given extensions, skipping node_modules."""
    files = []
    for ext in extensions:
        for f in root.rglob(f"*{ext}"):
            if "node_modules" in f.parts or "dist" in f.parts or "build" in f.parts:
                continue
            files.append(f)
    return files


def _read_safe(path: Path) -> str:
    """Read a file, returning empty string on error."""
    try:
        return path.read_text(encoding="utf-8", errors="replace")
    except (OSError, PermissionError):
        return ""


def _rel(root: Path, path: Path) -> str:
    """Return relative path string."""
    try:
        return str(path.relative_to(root))
    except ValueError:
        return str(path)


# ---------------------------------------------------------------------------
# Individual detectors
# ---------------------------------------------------------------------------

def _detect_empty_state_subcomponents(root: Path) -> list[dict[str, Any]]:
    """Detect EmptyStateHeader/EmptyStateIcon used in JSX (not just imported)."""
    issues = []
    pattern = re.compile(r"<(EmptyStateHeader|EmptyStateIcon)\b")
    for f in _source_files(root, (".tsx", ".jsx")):
        content = _read_safe(f)
        for m in pattern.finditer(content):
            lineno = content[:m.start()].count("\n") + 1
            component = m.group(1)
            line_text = content.splitlines()[lineno - 1].strip() if lineno <= len(content.splitlines()) else ""
            issues.append({
                "id": _make_id("empty-state-subcomponent", _rel(root, f), str(lineno)),
                "source": "source_detector",
                "severity": "warning",
                "file": _rel(root, f),
                "line": lineno,
                "title": f"{component} is removed in PF6",
                "detail": (
                    f"{component} was removed in PatternFly 6. "
                    "Use titleText, headingLevel, and icon props directly on EmptyState."
                ),
                "evidence": line_text,
                "suggestion": (
                    "Remove <EmptyStateHeader> and <EmptyStateIcon> and pass "
                    "titleText, headingLevel, and icon as props on <EmptyState>."
                ),
            })
    return issues


def _detect_button_icon_children(root: Path) -> list[dict[str, Any]]:
    """Detect Button components with icon children instead of icon prop."""
    issues = []
    # Look for patterns like <Button ...><SomeIcon /></Button> without icon= prop
    button_with_icon_child = re.compile(
        r"<Button\b(?![^>]*\bicon\s*=)[^>]*>\s*<\w+Icon\s*/?\s*>",
        re.DOTALL,
    )
    for f in _source_files(root, (".tsx", ".jsx")):
        content = _read_safe(f)
        for m in button_with_icon_child.finditer(content):
            lineno = content[:m.start()].count("\n") + 1
            issues.append({
                "id": _make_id("button-icon-child", _rel(root, f), str(lineno)),
                "source": "source_detector",
                "severity": "warning",
                "file": _rel(root, f),
                "line": lineno,
                "title": "Button icon should use icon prop, not children",
                "detail": (
                    "In PF6, icons should be passed to Button's `icon` prop "
                    "instead of as children."
                ),
                "evidence": m.group(0)[:120],
                "suggestion": "Move the icon from children to the `icon` prop: <Button icon={<SomeIcon />}>",
            })
    return issues


def _detect_mixed_pf_versions(root: Path) -> list[dict[str, Any]]:
    """Check package.json for mixed PF5/PF6 dependency versions."""
    issues = []
    pkg_json = root / "package.json"
    if not pkg_json.exists():
        return issues

    try:
        pkg = json.loads(_read_safe(pkg_json))
    except json.JSONDecodeError:
        return issues

    all_deps = {}
    for section in ("dependencies", "devDependencies", "peerDependencies"):
        all_deps.update(pkg.get(section, {}))

    pf_packages = {k: v for k, v in all_deps.items() if k.startswith("@patternfly/")}
    if not pf_packages:
        return issues

    v5_pkgs = []
    v6_pkgs = []
    for name, version in pf_packages.items():
        version_str = str(version)
        if re.search(r"[~^]?5\.", version_str) or version_str.startswith("5"):
            v5_pkgs.append(name)
        elif re.search(r"[~^]?6\.", version_str) or version_str.startswith("6"):
            v6_pkgs.append(name)

    if v5_pkgs and v6_pkgs:
        issues.append({
            "id": _make_id("mixed-pf-versions", "package.json"),
            "source": "source_detector",
            "severity": "critical",
            "file": "package.json",
            "line": None,
            "title": "Mixed PatternFly v5 and v6 dependencies",
            "detail": (
                f"Found v5 packages: {', '.join(v5_pkgs[:5])}. "
                f"Found v6 packages: {', '.join(v6_pkgs[:5])}. "
                "All @patternfly/* packages must be the same major version."
            ),
            "evidence": json.dumps({k: all_deps[k] for k in (v5_pkgs + v6_pkgs)[:6]}, indent=2),
            "suggestion": "Update all @patternfly/* packages to ^6.",
        })

    # Check if any key packages are still on v5
    key_packages = [
        "@patternfly/react-core",
        "@patternfly/patternfly",
        "@patternfly/react-icons",
        "@patternfly/react-table",
    ]
    for pkg_name in key_packages:
        if pkg_name in pf_packages:
            ver = str(pf_packages[pkg_name])
            if re.search(r"[~^]?5\.", ver) or ver.startswith("5"):
                issues.append({
                    "id": _make_id("key-pkg-v5", pkg_name),
                    "source": "source_detector",
                    "severity": "critical",
                    "file": "package.json",
                    "line": None,
                    "title": f"{pkg_name} still on v5",
                    "detail": f"{pkg_name} is version {ver}, should be ^6.",
                    "evidence": f'"{pkg_name}": "{ver}"',
                    "suggestion": f"Update {pkg_name} to ^6.",
                })

    return issues


def _detect_text_to_content_migration(root: Path) -> list[dict[str, Any]]:
    """Detect incomplete Text→Content migration patterns."""
    issues = []
    # Check for files that import Text but not Content, or use <Text> in JSX
    text_import = re.compile(
        r"import\s+\{[^}]*\b(Text|TextContent|TextList|TextListItem)\b[^}]*\}\s+from\s+['\"]@patternfly/react-core['\"]"
    )
    for f in _source_files(root, (".tsx", ".ts", ".jsx", ".js")):
        content = _read_safe(f)
        for m in text_import.finditer(content):
            lineno = content[:m.start()].count("\n") + 1
            component = m.group(1)
            line_text = content.splitlines()[lineno - 1].strip() if lineno <= len(content.splitlines()) else ""
            issues.append({
                "id": _make_id("text-import-not-migrated", _rel(root, f), component),
                "source": "source_detector",
                "severity": "warning",
                "file": _rel(root, f),
                "line": lineno,
                "title": f"Importing deprecated {component} from @patternfly/react-core",
                "detail": (
                    f"{component} has been renamed/replaced in PF6. "
                    "Use the Content component instead."
                ),
                "evidence": line_text,
                "suggestion": (
                    "Replace Text/TextContent/TextList/TextListItem imports "
                    "with Content from @patternfly/react-core."
                ),
            })
    return issues


def _detect_charts_import(root: Path) -> list[dict[str, Any]]:
    """Detect old @patternfly/react-charts imports (should use /victory subpath)."""
    issues = []
    old_import = re.compile(
        r"from\s+['\"]@patternfly/react-charts['\"]"
    )
    for f in _source_files(root):
        content = _read_safe(f)
        for m in old_import.finditer(content):
            lineno = content[:m.start()].count("\n") + 1
            line_text = content.splitlines()[lineno - 1].strip() if lineno <= len(content.splitlines()) else ""
            # Make sure it's not already using /victory
            if "/victory" in line_text:
                continue
            issues.append({
                "id": _make_id("charts-import", _rel(root, f), str(lineno)),
                "source": "source_detector",
                "severity": "warning",
                "file": _rel(root, f),
                "line": lineno,
                "title": "Charts import path changed in PF6",
                "detail": (
                    "In PF6, Victory-based charts moved to a subdirectory. "
                    "Import from '@patternfly/react-charts/victory' instead."
                ),
                "evidence": line_text,
                "suggestion": "Change import path to '@patternfly/react-charts/victory'.",
            })
    return issues


def _detect_toolbar_chip_props(root: Path) -> list[dict[str, Any]]:
    """Detect toolbar chip-related props that should be renamed to label."""
    issues = []
    chip_props = {
        "customChipGroupContent": "customLabelGroupContent",
        "deleteChipGroup": "deleteLabelGroup",
        "deleteChip": "deleteLabel",
        "chipGroupCollapsedText": "labelGroupCollapsedText",
        "chipGroupExpandedText": "labelGroupExpandedText",
    }
    prop_pattern = re.compile(r"\b(" + "|".join(chip_props.keys()) + r")\b")
    for f in _source_files(root, (".tsx", ".jsx")):
        content = _read_safe(f)
        for m in prop_pattern.finditer(content):
            lineno = content[:m.start()].count("\n") + 1
            old_prop = m.group(1)
            new_prop = chip_props[old_prop]
            line_text = content.splitlines()[lineno - 1].strip() if lineno <= len(content.splitlines()) else ""
            # Skip import lines
            if re.search(r"\bimport\b|\bfrom\b", line_text):
                continue
            issues.append({
                "id": _make_id("toolbar-chip-prop", _rel(root, f), f"{old_prop}:{lineno}"),
                "source": "source_detector",
                "severity": "warning",
                "file": _rel(root, f),
                "line": lineno,
                "title": f"Toolbar prop '{old_prop}' renamed to '{new_prop}'",
                "detail": (
                    f"In PF6, chip-related toolbar props were renamed to use 'label' terminology. "
                    f"'{old_prop}' should be '{new_prop}'."
                ),
                "evidence": line_text,
                "suggestion": f"Rename '{old_prop}' to '{new_prop}'.",
            })
    return issues


def _detect_page_prop_renames(root: Path) -> list[dict[str, Any]]:
    """Detect Page component props that were renamed in PF6."""
    issues = []
    renames = {
        "isTertiaryNavGrouped": "isHorizontalSubnavGrouped",
        "isTertiaryNavWidthLimited": "isHorizontalSubnavWidthLimited",
        "tertiaryNav": "horizontalSubnav",
    }
    prop_pattern = re.compile(r"\b(" + "|".join(renames.keys()) + r")\b")
    for f in _source_files(root, (".tsx", ".jsx")):
        content = _read_safe(f)
        for m in prop_pattern.finditer(content):
            lineno = content[:m.start()].count("\n") + 1
            old_prop = m.group(1)
            new_prop = renames[old_prop]
            line_text = content.splitlines()[lineno - 1].strip() if lineno <= len(content.splitlines()) else ""
            if re.search(r"\bimport\b|\bfrom\b", line_text):
                continue
            issues.append({
                "id": _make_id("page-prop-rename", _rel(root, f), f"{old_prop}:{lineno}"),
                "source": "source_detector",
                "severity": "warning",
                "file": _rel(root, f),
                "line": lineno,
                "title": f"Page prop '{old_prop}' renamed to '{new_prop}'",
                "detail": f"In PF6, '{old_prop}' was renamed to '{new_prop}'.",
                "evidence": line_text,
                "suggestion": f"Rename '{old_prop}' to '{new_prop}'.",
            })
    return issues


def _detect_removed_component_imports(root: Path) -> list[dict[str, Any]]:
    """Detect imports of components that were fully removed in PF6."""
    issues = []
    removed = [
        "ApplicationLauncher",
        "ContextSelector",
        "OptionsMenu",
        "KebabToggle",
        "PageNavigation",
    ]
    pattern = re.compile(
        r"import\s+\{[^}]*\b(" + "|".join(removed) + r")\b[^}]*\}\s+from\s+['\"]@patternfly/"
    )
    for f in _source_files(root):
        content = _read_safe(f)
        for m in pattern.finditer(content):
            lineno = content[:m.start()].count("\n") + 1
            component = m.group(1)
            line_text = content.splitlines()[lineno - 1].strip() if lineno <= len(content.splitlines()) else ""
            issues.append({
                "id": _make_id("removed-component-import", _rel(root, f), f"{component}:{lineno}"),
                "source": "source_detector",
                "severity": "high",
                "file": _rel(root, f),
                "line": lineno,
                "title": f"Importing removed component: {component}",
                "detail": (
                    f"{component} was removed in PF6 with no direct replacement. "
                    "Manual migration to a different component pattern is required."
                ),
                "evidence": line_text,
                "suggestion": f"Replace {component} with the recommended alternative (e.g., Dropdown + MenuToggle).",
            })
    return issues


def _detect_deprecated_import_barrel(root: Path) -> list[dict[str, Any]]:
    """Detect heavy reliance on @patternfly/react-core/deprecated barrel import."""
    issues = []
    deprecated_import = re.compile(
        r"import\s+\{([^}]+)\}\s+from\s+['\"]@patternfly/react-core/deprecated['\"]"
    )
    for f in _source_files(root):
        content = _read_safe(f)
        for m in deprecated_import.finditer(content):
            lineno = content[:m.start()].count("\n") + 1
            imported_names = [n.strip() for n in m.group(1).split(",") if n.strip()]
            line_text = content.splitlines()[lineno - 1].strip() if lineno <= len(content.splitlines()) else ""
            issues.append({
                "id": _make_id("deprecated-barrel", _rel(root, f), str(lineno)),
                "source": "source_detector",
                "severity": "info",
                "file": _rel(root, f),
                "line": lineno,
                "title": f"Using deprecated import ({len(imported_names)} components)",
                "detail": (
                    f"Importing {', '.join(imported_names[:3])}{'...' if len(imported_names) > 3 else ''} "
                    "from @patternfly/react-core/deprecated. These should be migrated to their "
                    "PF6 replacements."
                ),
                "evidence": line_text,
                "suggestion": "Migrate each deprecated component to its PF6 replacement.",
            })
    return issues


def _detect_css_var_prefixes(root: Path) -> list[dict[str, Any]]:
    """Detect --pf-v5- CSS variable usage in stylesheets."""
    issues = []
    pattern = re.compile(r"--pf-v5-[a-zA-Z0-9_-]+")
    for f in _source_files(root, (".css", ".scss", ".tsx", ".ts", ".jsx", ".js")):
        content = _read_safe(f)
        matches = list(pattern.finditer(content))
        if matches:
            # Group by file - report once per file with count
            lines = set()
            examples = []
            for m in matches[:5]:
                ln = content[:m.start()].count("\n") + 1
                lines.add(ln)
                examples.append(m.group(0))
            issues.append({
                "id": _make_id("css-var-v5-prefix", _rel(root, f)),
                "source": "source_detector",
                "severity": "warning",
                "file": _rel(root, f),
                "line": min(lines) if lines else None,
                "title": f"PF5 CSS variables found ({len(matches)} occurrences)",
                "detail": (
                    f"Found {len(matches)} uses of --pf-v5-* CSS variables. "
                    "These must be updated to --pf-v6-* or the new design token equivalents."
                ),
                "evidence": ", ".join(examples[:3]),
                "suggestion": "Run the css-vars-updater codemod or manually update to PF6 token names.",
            })
    return issues


# ---------------------------------------------------------------------------
# Main entry point
# ---------------------------------------------------------------------------

def detect(root: Path) -> list[dict[str, Any]]:
    """Scan the codebase at `root` for PatternFly 5→6 migration issues.

    Returns a list of issue dicts compatible with the migeval Issue model.
    """
    all_issues: list[dict[str, Any]] = []

    detectors = [
        _detect_mixed_pf_versions,
        _detect_empty_state_subcomponents,
        _detect_button_icon_children,
        _detect_text_to_content_migration,
        _detect_charts_import,
        _detect_toolbar_chip_props,
        _detect_page_prop_renames,
        _detect_removed_component_imports,
        _detect_deprecated_import_barrel,
        _detect_css_var_prefixes,
    ]

    for detector_fn in detectors:
        try:
            all_issues.extend(detector_fn(root))
        except Exception:
            # Silently skip failing detectors to avoid breaking the pipeline
            pass

    return all_issues
