# Generated by migeval bootstrap — review before committing
"""
AST-aware detectors for PatternFly 5 → 6 migration issues.

Scans source files for patterns that text_patterns cannot easily catch,
including cross-file consistency checks and context-aware prop validation.
"""
from pathlib import Path
from typing import Any
import hashlib
import json
import re

# File extensions to scan
SOURCE_EXTS = {".tsx", ".ts", ".jsx", ".js"}
STYLE_EXTS = {".css", ".scss"}
ALL_EXTS = SOURCE_EXTS | STYLE_EXTS


def make_issue_id(detector_id: str, file: str, extra: str = "") -> str:
    """Generate a deterministic issue ID."""
    key = f"source_detector|{detector_id}|{file}|{extra}"
    return hashlib.sha256(key.encode()).hexdigest()[:16]


def walk_files(root: Path, extensions: set[str]):
    """Yield (relative_path, full_path) for files matching extensions."""
    for p in root.rglob("*"):
        if p.is_file() and p.suffix in extensions:
            # Skip node_modules, build, dist
            parts = p.relative_to(root).parts
            if any(skip in parts for skip in ("node_modules", "build", "dist", ".git")):
                continue
            yield str(p.relative_to(root)), p


def read_file_safe(path: Path) -> str:
    """Read file contents safely, returning empty string on error."""
    try:
        return path.read_text(encoding="utf-8", errors="replace")
    except (OSError, PermissionError):
        return ""


def check_package_json(root: Path) -> list[dict[str, Any]]:
    """Check that @patternfly packages are updated to v6."""
    issues = []
    pkg_path = root / "package.json"
    if not pkg_path.exists():
        return issues

    try:
        pkg = json.loads(pkg_path.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError):
        return issues

    all_deps = {}
    for section in ("dependencies", "devDependencies", "peerDependencies"):
        all_deps.update(pkg.get(section, {}))

    pf_packages = [
        "@patternfly/patternfly",
        "@patternfly/react-core",
        "@patternfly/react-icons",
        "@patternfly/react-styles",
        "@patternfly/react-table",
        "@patternfly/react-tokens",
    ]

    for pf_pkg in pf_packages:
        version = all_deps.get(pf_pkg, "")
        if not version:
            continue
        # Check if version looks like v5 (starts with 5, ^5, ~5)
        clean = version.lstrip("^~>=<")
        if clean.startswith("5"):
            issues.append({
                "id": make_issue_id("pkg-version", pf_pkg),
                "source": "source_detector",
                "severity": "critical",
                "file": "package.json",
                "line": None,
                "title": f"{pf_pkg} still at PF5 version",
                "detail": f"Package {pf_pkg} has version '{version}' which is PatternFly 5. Must be updated to ^6 for PF6 migration.",
                "evidence": f'"{pf_pkg}": "{version}"',
                "suggestion": f'Update to "{pf_pkg}": "^6" in package.json.',
            })
        elif not clean.startswith("6"):
            # Could be other major, flag as info
            pass

    return issues


def check_emptystate_old_pattern(root: Path) -> list[dict[str, Any]]:
    """Detect old EmptyState patterns that need restructuring for PF6.

    Checks for:
    1. EmptyStateIcon used as a JSX child element
    2. Title used inside EmptyState
    3. EmptyStateHeader used as a JSX child element
    """
    issues = []
    # Pattern: <EmptyStateIcon used as JSX (not just imported)
    icon_jsx_re = re.compile(r"<EmptyStateIcon\s")
    header_jsx_re = re.compile(r"<EmptyStateHeader\b")
    title_in_emptystate_re = re.compile(r"<Title\b")

    # Track if file has EmptyState context
    emptystate_import_re = re.compile(
        r"from\s+['\"]@patternfly/react-core['\"]"
    )

    for rel, full in walk_files(root, SOURCE_EXTS):
        content = read_file_safe(full)
        if not content or "EmptyState" not in content:
            continue

        lines = content.split("\n")
        for i, line in enumerate(lines, 1):
            if icon_jsx_re.search(line):
                issues.append({
                    "id": make_issue_id("emptystate-icon-jsx", rel, str(i)),
                    "source": "source_detector",
                    "severity": "high",
                    "file": rel,
                    "line": i,
                    "title": "EmptyStateIcon used as JSX child (removed in PF6)",
                    "detail": (
                        "EmptyStateIcon is no longer a standalone component in PF6. "
                        "Pass the icon directly to EmptyState's icon prop."
                    ),
                    "evidence": line.strip(),
                    "suggestion": "Replace <EmptyStateIcon icon={Icon} /> with icon={Icon} prop on <EmptyState>.",
                })

            if header_jsx_re.search(line):
                # Skip import lines
                if "import" in line and "from" in line:
                    continue
                issues.append({
                    "id": make_issue_id("emptystate-header-jsx", rel, str(i)),
                    "source": "source_detector",
                    "severity": "high",
                    "file": rel,
                    "line": i,
                    "title": "EmptyStateHeader used as JSX child (removed in PF6)",
                    "detail": (
                        "EmptyStateHeader is no longer exported in PF6. Use titleText, "
                        "headingLevel, and icon props directly on EmptyState."
                    ),
                    "evidence": line.strip(),
                    "suggestion": "Move titleText, headingLevel, icon to EmptyState props.",
                })

    return issues


def check_modal_import_path(root: Path) -> list[dict[str, Any]]:
    """Detect Modal imported from @patternfly/react-core (not /deprecated)."""
    issues = []
    modal_from_core_re = re.compile(
        r"import\s+\{[^}]*\bModal\b[^}]*\}\s+from\s+['\"]@patternfly/react-core['\"]"
    )

    for rel, full in walk_files(root, SOURCE_EXTS):
        content = read_file_safe(full)
        if not content or "Modal" not in content:
            continue

        lines = content.split("\n")
        # Check multi-line imports by joining
        full_content = content
        for m in modal_from_core_re.finditer(full_content):
            # Find line number
            line_num = full_content[:m.start()].count("\n") + 1
            issues.append({
                "id": make_issue_id("modal-import-core", rel),
                "source": "source_detector",
                "severity": "high",
                "file": rel,
                "line": line_num,
                "title": "Modal imported from @patternfly/react-core (must use /deprecated or new API)",
                "detail": (
                    "In PF6, the old Modal is moved to @patternfly/react-core/deprecated. "
                    "Import from there or migrate to the new Modal composition API."
                ),
                "evidence": m.group(0)[:120],
                "suggestion": "Change import to: import { Modal } from '@patternfly/react-core/deprecated';",
            })

    return issues


def check_text_components(root: Path) -> list[dict[str, Any]]:
    """Detect TextContent/TextList/TextListItem usage that needs Content migration."""
    issues = []
    text_jsx_re = re.compile(r"<(TextContent|TextList|TextListItem)\b")

    for rel, full in walk_files(root, SOURCE_EXTS):
        content = read_file_safe(full)
        if not content:
            continue

        has_text_component = any(
            t in content for t in ("TextContent", "TextList", "TextListItem")
        )
        if not has_text_component:
            continue

        lines = content.split("\n")
        for i, line in enumerate(lines, 1):
            # Skip import lines
            if "import" in line and "from" in line:
                continue
            match = text_jsx_re.search(line)
            if match:
                component = match.group(1)
                issues.append({
                    "id": make_issue_id("text-component-jsx", rel, f"{component}-{i}"),
                    "source": "source_detector",
                    "severity": "high",
                    "file": rel,
                    "line": i,
                    "title": f"{component} removed in PF6 — use Content",
                    "detail": (
                        f"PF6 replaces {component} with the unified Content component. "
                        "TextContent → Content, TextList → Content with component prop, "
                        "TextListItem → native HTML elements inside Content."
                    ),
                    "evidence": line.strip(),
                    "suggestion": f"Replace <{component}> with <Content> and appropriate component prop.",
                })

    return issues


def check_react_tokens(root: Path) -> list[dict[str, Any]]:
    """Detect old PF5 react-token names that need PF6 updates."""
    issues = []
    old_tokens = {
        "global_Color_dark_100": "t_global_text_color_regular",
        "global_success_color_100": "t_global_color_status_success_default",
        "global_warning_color_100": "t_global_color_status_warning_default",
        "global_danger_color_100": "t_global_color_status_danger_default",
        "global_danger_color_200": "t_global_color_status_danger_hover",
        "global_link_Color": "t_global_color_nonstatus_blue_default",
        "global_link_Color_hover": "t_global_color_nonstatus_blue_hover",
    }

    token_import_re = re.compile(r"from\s+['\"]@patternfly/react-tokens['\"]")

    for rel, full in walk_files(root, SOURCE_EXTS):
        content = read_file_safe(full)
        if not content or "@patternfly/react-tokens" not in content:
            continue

        lines = content.split("\n")
        for i, line in enumerate(lines, 1):
            for old_name, new_name in old_tokens.items():
                if old_name in line:
                    issues.append({
                        "id": make_issue_id("old-token", rel, f"{old_name}-{i}"),
                        "source": "source_detector",
                        "severity": "medium",
                        "file": rel,
                        "line": i,
                        "title": f"PF5 token '{old_name}' needs PF6 update",
                        "detail": (
                            f"The react-token '{old_name}' is renamed in PF6. "
                            f"The approximate PF6 equivalent is '{new_name}', but verify "
                            "against the PF6 token documentation."
                        ),
                        "evidence": line.strip(),
                        "suggestion": f"Replace '{old_name}' with '{new_name}' from @patternfly/react-tokens.",
                    })

    return issues


def check_css_prefixes(root: Path) -> list[dict[str, Any]]:
    """Detect pf-v5- CSS class prefixes and --pf-v5- CSS variable prefixes."""
    issues = []
    class_re = re.compile(r"pf-v5-[\w-]+")
    var_re = re.compile(r"--pf-v5-[\w-]+")

    for rel, full in walk_files(root, ALL_EXTS):
        content = read_file_safe(full)
        if not content or "pf-v5" not in content:
            continue

        # Skip snapshot files
        if ".snap" in rel:
            continue

        lines = content.split("\n")
        reported_classes = set()
        for i, line in enumerate(lines, 1):
            for m in class_re.finditer(line):
                cls = m.group(0)
                if cls not in reported_classes:
                    reported_classes.add(cls)
                    issues.append({
                        "id": make_issue_id("css-v5-class", rel, cls),
                        "source": "source_detector",
                        "severity": "high",
                        "file": rel,
                        "line": i,
                        "title": f"PF5 CSS class '{cls}' must be updated to pf-v6-",
                        "detail": f"The CSS class '{cls}' uses the pf-v5- prefix which must be pf-v6- in PatternFly 6.",
                        "evidence": line.strip(),
                        "suggestion": f"Replace '{cls}' with '{cls.replace('pf-v5-', 'pf-v6-')}'.",
                    })

            for m in var_re.finditer(line):
                var = m.group(0)
                issues.append({
                    "id": make_issue_id("css-v5-var", rel, f"{var}-{i}"),
                    "source": "source_detector",
                    "severity": "high",
                    "file": rel,
                    "line": i,
                    "title": f"PF5 CSS variable '{var}' must be updated",
                    "detail": f"CSS variable '{var}' uses --pf-v5- prefix. Must be updated to --pf-v6- equivalent.",
                    "evidence": line.strip(),
                    "suggestion": f"Replace '{var}' with the --pf-v6- equivalent.",
                })

    return issues


def check_pagesection_variant(root: Path) -> list[dict[str, Any]]:
    """Detect PageSection with variant='light' which is removed in PF6."""
    issues = []
    variant_light_re = re.compile(r'<PageSection[^>]*variant=["\']light["\']')

    for rel, full in walk_files(root, SOURCE_EXTS):
        content = read_file_safe(full)
        if not content or "PageSection" not in content:
            continue

        lines = content.split("\n")
        for i, line in enumerate(lines, 1):
            if variant_light_re.search(line):
                issues.append({
                    "id": make_issue_id("pagesection-variant-light", rel, str(i)),
                    "source": "source_detector",
                    "severity": "medium",
                    "file": rel,
                    "line": i,
                    "title": "PageSection variant='light' removed in PF6",
                    "detail": "PF6 removes 'light' variant from PageSection. Use 'default' or omit the prop.",
                    "evidence": line.strip(),
                    "suggestion": "Change variant='light' to variant='default' or remove the variant prop.",
                })

    return issues


def check_deprecated_imports(root: Path) -> list[dict[str, Any]]:
    """Detect imports from @patternfly/react-core/deprecated — these components
    are removed in PF6 (the /deprecated path no longer exists)."""
    issues = []
    deprecated_re = re.compile(
        r"from\s+['\"]@patternfly/react-core/deprecated['\"]"
    )

    for rel, full in walk_files(root, SOURCE_EXTS):
        content = read_file_safe(full)
        if not content or "/deprecated" not in content:
            continue

        lines = content.split("\n")
        for i, line in enumerate(lines, 1):
            if deprecated_re.search(line):
                # Extract what's being imported
                import_match = re.search(r"import\s+\{([^}]+)\}", line)
                components = import_match.group(1).strip() if import_match else "unknown"
                issues.append({
                    "id": make_issue_id("deprecated-import", rel, str(i)),
                    "source": "source_detector",
                    "severity": "warning",
                    "file": rel,
                    "line": i,
                    "title": f"Deprecated PF5 components still in use: {components}",
                    "detail": (
                        "Components imported from @patternfly/react-core/deprecated "
                        "are legacy PF5 components. While they may still work in PF6 "
                        "temporarily, they should be migrated to current equivalents."
                    ),
                    "evidence": line.strip(),
                    "suggestion": "Migrate to the current PF6 equivalent components.",
                })

    return issues


def check_emptystate_variant_full(root: Path) -> list[dict[str, Any]]:
    """Detect EmptyStateVariant.full which is removed in PF6."""
    issues = []
    variant_full_re = re.compile(r"EmptyStateVariant\.full\b")
    variant_str_full_re = re.compile(r'variant=["\']full["\']')

    for rel, full_path in walk_files(root, SOURCE_EXTS):
        content = read_file_safe(full_path)
        if not content or "EmptyState" not in content:
            continue

        lines = content.split("\n")
        for i, line in enumerate(lines, 1):
            if variant_full_re.search(line) or variant_str_full_re.search(line):
                issues.append({
                    "id": make_issue_id("emptystate-variant-full", rel, str(i)),
                    "source": "source_detector",
                    "severity": "medium",
                    "file": rel,
                    "line": i,
                    "title": "EmptyStateVariant.full removed in PF6",
                    "detail": "The 'full' variant is removed from EmptyState in PF6. Use 'lg' or remove the variant prop.",
                    "evidence": line.strip(),
                    "suggestion": "Replace EmptyStateVariant.full / variant='full' with variant='lg' or remove it.",
                })

    return issues


def detect(root: Path) -> list[dict[str, Any]]:
    """Main entry point: scan the codebase at `root` for PF5→PF6 migration issues.

    Returns a list of issue dicts matching the Issue model.
    """
    issues: list[dict[str, Any]] = []

    detectors = [
        check_package_json,
        check_emptystate_old_pattern,
        check_emptystate_variant_full,
        check_modal_import_path,
        check_text_components,
        check_react_tokens,
        check_css_prefixes,
        check_pagesection_variant,
        check_deprecated_imports,
    ]

    for detector_fn in detectors:
        try:
            issues.extend(detector_fn(root))
        except Exception as e:
            # Gracefully handle detector failures
            issues.append({
                "id": make_issue_id("detector-error", detector_fn.__name__),
                "source": "source_detector",
                "severity": "info",
                "file": "",
                "line": None,
                "title": f"Detector '{detector_fn.__name__}' failed: {type(e).__name__}",
                "detail": str(e),
                "evidence": "",
                "suggestion": "Check detector implementation.",
            })

    return issues
